---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-adapter
  name: prometheus-adapter
  namespace: monitoring
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: prometheus-adapter
  type: ClusterIP
