---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: demo
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - image: aputra/express-073:latest
        name: express
        ports:
        - name: http
          containerPort: 8081
