---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-app
  namespace: demo
  labels:
    team: devops
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      app: sample-app
