---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: monitoring
  labels:
    app: express
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: http
  selector:
    app: express
