---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-test
  namespace: monitoring
  labels:
    team: devops
spec:
  endpoints:
  - port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: express
